/**
 * 🇰🇪 KRA Tax Return & Compliance Utility
 * Generated by Stitch & Styles Kenya
 */

const KRA_TAX_TYPES = {
    tot: { label: "Turnover Tax (TOT 3%)", rate: 0.03, description: "For small businesses (KES 1M - 25M turnover)" },
    vat: { label: "Value Added Tax (VAT 16%)", rate: 0.16, description: "Standard VAT registration" },
    exempt: { label: "Exempt / Below KES 1M", rate: 0, description: "Small sole trader / Exempt sales" }
};

// Retrieve saved tax obligation
function getShopTaxObligation() {
    return localStorage.getItem('stitch_kra_tax_type') || 'tot';
}

// Update saved tax obligation
function setShopTaxObligation(taxType) {
    if (KRA_TAX_TYPES[taxType]) {
        localStorage.setItem('stitch_kra_tax_type', taxType);
        return true;
    }
    return false;
}

/**
 * Calculate KRA Tax details for a set of orders over a date period
 */
function calculateKRATaxData(orders = [], startDate = null, endDate = null) {
    const taxType = getShopTaxObligation();
    const config = KRA_TAX_TYPES[taxType] || KRA_TAX_TYPES.tot;

    // Filter valid paid/completed orders in range
    let validOrders = orders.filter(o => {
        const status = (o.status || '').toLowerCase();
        const paymentStatus = (o.payment_status || '').toLowerCase();
        // Include if marked paid, completed, delivered, or ready
        const isPaid = paymentStatus === 'paid' || status === 'completed' || status === 'delivered' || (o.paid_amount && o.paid_amount > 0);
        
        if (!isPaid) return false;

        if (startDate && endDate) {
            const orderDate = new Date(o.created_at || o.date || Date.now());
            return orderDate >= new Date(startDate) && orderDate <= new Date(endDate);
        }
        return true;
    });

    let grossSales = 0;
    validOrders.forEach(o => {
        const val = parseFloat(o.total_amount || o.amount || o.paid_amount || o.grand_total || 0);
        if (!isNaN(val)) grossSales += val;
    });

    let taxAmount = grossSales * config.rate;

    // KRA Deadline calculation (20th of next month relative to end date or current date)
    const refDate = endDate ? new Date(endDate) : new Date();
    let nextMonth = new Date(refDate.getFullYear(), refDate.getMonth() + 1, 20);
    const daysRemaining = Math.ceil((nextMonth - new Date()) / (1000 * 60 * 60 * 24));

    return {
        taxType,
        taxLabel: config.label,
        taxRate: config.rate,
        grossSales: Math.round(grossSales),
        taxAmount: Math.round(taxAmount),
        orderCount: validOrders.length,
        validOrders,
        deadlineDate: nextMonth.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }),
        daysRemaining
    };
}

/**
 * Open WhatsApp with pre-filled KRA Summary Message
 */
function shareKRAWhatsAppSummary(orders, startDate, endDate) {
    const data = calculateKRATaxData(orders, startDate, endDate);
    const shopName = (typeof currentOrg !== 'undefined' && currentOrg?.name) 
        || (typeof APP_CONFIG !== 'undefined' && APP_CONFIG.appName) 
        || "Stitch & Styles Kenya Shop";

    const periodStr = startDate && endDate 
        ? `${new Date(startDate).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })} - ${new Date(endDate).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}`
        : new Date().toLocaleDateString('en-GB', { month: 'long', year: 'numeric' });

    const msg = 
`🇰🇪 *KRA TAX RETURN SUMMARY*
📍 *Shop*: ${shopName}
📅 *Period*: ${periodStr}
🏷️ *Tax Type*: ${data.taxLabel}

💰 *Gross Sales*: KES ${data.grossSales.toLocaleString()}
📊 *Total Orders*: ${data.orderCount}
💵 *Estimated KRA Tax Payable*: KES ${data.taxAmount.toLocaleString()}
⏰ *Filing Deadline*: ${data.deadlineDate} (${data.daysRemaining > 0 ? data.daysRemaining + ' days left' : 'Due today/overdue'})

----------------------------
*Generated by tailors.co.ke*`;

    const encoded = encodeURIComponent(msg);
    window.open(`https://api.whatsapp.com/send?text=${encoded}`, '_blank');
}

/**
 * Download KRA iTax formatted CSV
 */
function downloadKRAiTaxCSV(orders, startDate, endDate) {
    const data = calculateKRATaxData(orders, startDate, endDate);
    
    let csvContent = "PIN of Buyer,Customer Name,Invoice Date,Invoice Number,Description,Gross Amount (KES),Tax Type,Tax Amount (KES)\n";

    if (data.validOrders.length === 0) {
        csvContent += `P000000000Z,Nil Sales,${new Date().toISOString().split('T')[0]},INV-NIL,No sales recorded,0,${data.taxLabel},0\n`;
    } else {
        data.validOrders.forEach(o => {
            const buyerPin = o.client_pin || o.kra_pin || "P000000000Z";
            const buyerName = (o.client_name || o.customer_name || "Walk-in Client").replace(/,/g, ' ');
            const invDate = (o.created_at || o.date || new Date().toISOString()).split('T')[0];
            const invNo = o.order_number || o.id || "INV-" + Math.floor(1000 + Math.random() * 9000);
            const desc = (o.item_name || o.description || o.service || "Tailoring Services").replace(/,/g, ' ');
            const amt = parseFloat(o.total_amount || o.amount || 0);
            const tax = Math.round(amt * data.taxRate);

            csvContent += `"${buyerPin}","${buyerName}","${invDate}","${invNo}","${desc}",${amt},"${data.taxLabel}",${tax}\n`;
        });
    }

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute("download", `KRA_iTax_Sales_Ledger_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
}

/**
 * Render/Update the KRA Tax Widget inside Financial Overview
 */
function updateKRATaxUIWidget(orders = [], startDate = null, endDate = null) {
    const data = calculateKRATaxData(orders, startDate, endDate);

    // Update Gross Sales
    const grossEl = document.getElementById('kra-gross-sales');
    if (grossEl) grossEl.textContent = `KES ${data.grossSales.toLocaleString()}`;

    // Update Tax Payable
    const taxEl = document.getElementById('kra-tax-payable');
    if (taxEl) taxEl.textContent = `KES ${data.taxAmount.toLocaleString()}`;

    // Update Rate Badge
    const rateEl = document.getElementById('kra-tax-rate-badge');
    if (rateEl) rateEl.textContent = `${(data.taxRate * 100).toFixed(0)}% Rate`;

    // Update Deadline Badge
    const deadlineEl = document.getElementById('kra-deadline-subtext');
    if (deadlineEl) {
        if (data.daysRemaining <= 5 && data.daysRemaining >= 0) {
            deadlineEl.innerHTML = `<span style="color: #ef4444; font-weight:700;"><i class="fas fa-exclamation-triangle"></i> Due in ${data.daysRemaining} days (${data.deadlineDate})</span>`;
        } else {
            deadlineEl.textContent = `Due ${data.deadlineDate} (${data.daysRemaining} days left)`;
        }
    }

    // Update Tax Type Select
    const selectEl = document.getElementById('kra-tax-type-select');
    if (selectEl && selectEl.value !== data.taxType) {
        selectEl.value = data.taxType;
    }

    // Attach actions to window for button clicks
    window._lastKRAOrders = orders;
    window._lastKRAStartDate = startDate;
    window._lastKRAEndDate = endDate;
}

// Global button handlers
window.handleKRATaxTypeChange = function(newType) {
    setShopTaxObligation(newType);
    updateKRATaxUIWidget(window._lastKRAOrders || [], window._lastKRAStartDate, window._lastKRAEndDate);
};

window.triggerKRAWhatsApp = function() {
    shareKRAWhatsAppSummary(window._lastKRAOrders || [], window._lastKRAStartDate, window._lastKRAEndDate);
};

window.triggerKRADownloadCSV = function() {
    downloadKRAiTaxCSV(window._lastKRAOrders || [], window._lastKRAStartDate, window._lastKRAEndDate);
};

// Initial sync on script load / DOMReady
if (typeof document !== 'undefined') {
    document.addEventListener('DOMContentLoaded', function() {
        const selectEl = document.getElementById('kra-tax-type-select');
        if (selectEl) {
            selectEl.value = getShopTaxObligation();
        }
        updateKRATaxUIWidget([], null, null);
    });
}
